### ISSUE TITLE
Registry

### ISSUE THREAD

**Issue by iLexiconn** [OpenModLoader/OpenModLoader#2]

**Comment by Caellian** [comment]
Is it possible to collect fuels registered by vanilla MC and mods. I believe just a HashMap of fuels to their tick burn time would be incredibly useful for all mods using them as fuels and it would make power systems less prone to breaking if any burn duration alterations occur in newer versions of Minecraft due to nerfing of vanill MC. I'll look into how much code is necessary and patching (and whatever...) for that tomorrow.

**Comment by darkhax** [comment]
@Caellian I don't see a problem with that, as long as it's done appropriately.

**Comment by darkhax** [comment]
This issue has no description, and various registry have already been added.
