### ISSUE TITLE
OreDictionary system

### ISSUE THREAD

**Issue by The-Fireplace** [OpenModLoader/OpenModLoader#31]
I know this is a very low priority feature at the moment, but I am going to go ahead and put this out there so it doesn't get forgotten.

We will need some kind of OreDictionary system to use with our recipes.

**Comment by iLexiconn** [comment]
I don't think we need them. Mods will have plenty of features to communicae with eachother.

**Comment by shadowfacts** [comment]
I don't think this is really necessary. The reason Forge has the OreDict is multiple mods added overlapping stuff before it was created. If we can create one standardized mod to contain common ore and ingots, then any mod that wants to use said ores/ingots can depend on that.

**Comment by iLexiconn** [comment]
That ^

**Comment by The-Fireplace** [comment]
@iLexiconn Alright, here's a likely scenario, I am curious to see how it would be handled without some kind of OreDictionary system.

Mod A and Mod B both add copper ingots. Mod A adds a recipe for one of its other items using its copper ingots. How do you use Mod B's ingots in Mod A's recipe?

**Comment by iLexiconn** [comment]
Did you read @shadowfacts's comment? ;p

**Comment by shadowfacts** [comment]
@The-Fireplace My point is both mods _don't_ add their own copper ingots, they use the ones provided by the base mod.

**Comment by The-Fireplace** [comment]
@shadowfacts so you plan to encompass every type of metal that might be added in more than one mod and hope that you don't miss any?

**Comment by darkhax** [comment]
@shadowfacts @iLexiconn You're making the assumption that the ore dictionary is for over lapping content, however that is just a very small part of what it is actually used for. The dictionary in forge is primarily used to give items different groups which can be used to reference them. For example, many mods add wooden fences, and many other mods including a few of my own have recipes that take advantage of the ore dictionary to add recipe support for all of them in one go. Situations like this are not weird corner cases, it is the primary use. There are plenty of other examples. Dyes, dirt, stone, cobblestone, dyes, bones, gunpowder, string, crops, leather are just a few examples. 

Also, even if a central mod could be created that has every single metal, we can't enforce that standard. There are tons of issues with the central mod concept, such as the textures being used may not fit with every mod that would have to use them. Even if we did go down the dependency route, what happens when mod A and mod B both add the same uncommon metal that isn't included in said dependency?

**Comment by shadowfacts** [comment]
Good point.

**Comment by darkhax** [comment]
A dictionary system has been added.
